### ISSUE TITLE
Просьба проверить домашнее задание

### ISSUE THREAD

**Issue by 4opper** [4opper/typing-practice#1]
Добрый день!
Вот [ветка](https://github.com/4opper/typing-practice/tree/homework-task)

Не придумал как для `getAvailableOperations` описать возвращаем тип на основании `availableOperations`. Это вообще возможно сделать? Если да, можно подсказку как это написать?

**Comment by JSMonk** [comment]
Здравствуйте, Роман.
Попробуйте поиграться с [этим примером](https://www.typescriptlang.org/play#code/MYewdgzgLgBApmArgWxgJRAGzjA3jAQQBEBZASQDkYAaGEgeSIFE0CAVetWgYQBkymFNjAC+AKFCRYCFDHoAHOACcAhlACW4PDACqABSLsmAfQ7G+AoTV0Gjp+sYbNWHLjcNsTZ4uSriJmCoQEIQAJsjqYHhiMLEw8krqAG5qOEpwKqHgmACeMMZQOYowALwwAMo5yABGWAAUAEQE4ZENAJQA3DFx6ZnZeUpYOGUY2AB0PpRd-sCBwXQgocpqIErRcfGJKVBpGVlgufmFxWWVNfUNJIvLUKvtXRu9+4eD2KXoQ2NOLOyc02IBIIhbiYdQIWC4bqxBLJVIwJ79I5FYYVKq1TCNEFgsBQe5Q+F7RGvFGjOBjCyCNj-MTHHA6CDKd7NCJRAA+MCx4Jg7KuS1UtyUXVpMD0W3U2AA5nBQvTGWVmZFuQs+StBQCAPTqmCAHBBAHwggDYQQC8ILqYIBREEAAiCABhBDYAOEEAQiCAGRAYIAuEEtzpgurtgBYQQCsIIBuEAdhsAwiCAORAXbrDYAREBtgGYQINWwBiIDaw4AmEBdbt1gB4QAC0dpNkctgE4QP0+iTgaCEABqBDIvAIACFeCZ6HofmwyPQKOV3pCNgBtUnk-iUgC6AC51hs4gPPpMKOOYH2R9R8f3B98XJwF0uV1Pp4OKUJtyP8SJd-vPhvfmgF7294vB3Pj+e9zPxlfXNuFDdNGAxvoPC8BxDzYZdVwvcYQK-RR+V-f9bE8exHEYNst1PF8H1nUhKFvcDYjfMknwnPtv1g8B4MApCPy3DC10vFDNxvYjSLUOCALsMwQNoFiNHI9jEO8bD51oiCySg5iYNYviEKA5DnGvE8NnEEQYCCGBJGgLoaWRKsazrRtm1bFwOy7d5aRAAAzXTawbJtjBbNsTPKLSLMQMBgF4qIpSgAgUnFFRqmwHjfwgAAeGB8R0ABGeAAA8djAUIQllJQMJ0AAmOKEqSkUxUlaUUpXAA+OpEAZJQJ2i2hgEQJR0hxFLKvStpJ3SKBaqiAhqxsgz7KM9gnL7Gq6vBFKxmJEc+zK5RxqGEdVJCLq9NswzHM7co+wyvsGmJBoR0m6Ltt2-bqVc9zPJgabgvAULoqyhAcsK3RMrgeKHpCUVknFOApRlcqSumirdCi6ravqqBGuelq7zajqYG83yVH8wK4GuyBSvK0GRoa8rOjEfxNRgQAEEBgO0gztGAg31H0YENGnM0tQB+EEZ+1AEEQQB5EHDc1zR9Z07WNGnAHYQQ1LUAcRAfVtGmU11QWUytQBJEEtH1M11GMTWdXVzTtH19UtMYYEAfBBzRtU1dS9NnOZZ1nLUdD1AEYQXU7flwBFEENQ1AGkQQtSZtRn9bLKRVPeK7JM8uowDgAB3ZUblWOo2locOo4VMA47xoA)

**Comment by 4opper** [comment]
@JSMonk Добрый день. Спасибо за ссылку, помогло.
Обновил типы для `getAvailableOperations ` согласно примеру.  Прошу проверить

**Comment by JSMonk** [comment]
Здравствуйте, Роман.

1. Клиент может залогиниться тоже ([здесь](https://github.com/JSMonk/typing-practice/compare/homework-task...4opper:homework-task#diff-586fbcdbd6547954463562f3e9b420c6296b700ddacc6daf81634f4c51a8756cR55) Вы это явно запрещаете), просто не имеет доступа конкретно к Dashboard странице.
2. Давайте попробуем вынести классы `ValidEmail` и `ValidPassword` в отдельние файли.

Все остальное очень хорошо. Отличная работа 👍

**Comment by 4opper** [comment]
@JSMonk Здравствуйте, Артём. 

Спасибо, обновил.

**Comment by JSMonk** [comment]
Да, все хорошо.
Задача зачтена.
